---
abstract: "Convert TBX-Basic data into TBX-Min\r"
author:
  - 'BYU Translation Research Group <akmtrg@byu.edu>'
build_requires:
  Capture::Tiny: 0
  Data::Section::Simple: 0
  Devel::FindPerl: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Log::Any::Test: 0
  Module::Build: 0.3601
  Test::Base: 0
  Test::Exception: 0
  Test::LongString: 0
  Test::More: 0.88
  Test::NoWarnings: 0
  Test::XML: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Convert-TBX-Basic
no_index:
  directory:
    - 'inc t xt examples share eg mylib'
provides:
  Convert::TBX::Basic:
    file: lib/Convert/TBX/Basic.pm
    version: 0.02
requires:
  Carp: 0
  Exporter::Easy: 0
  Log::Any: 0
  Log::Any::Adapter: 0
  Path::Tiny: 0
  TBX::Min: 0.06
  Try::Tiny: 0
  XML::Twig: 0
  autodie: 0
  perl: 5.009005
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Convert-TBX-Basic
  homepage: https://github.com/byutrg/p5-Convert-TBX-Basic
  license: http://dev.perl.org/licenses/
  repository: https://github.com/byutrg/p5-Convert-TBX-Basic.git
version: 0.02
x_BuiltWith:
  modules:
    Capture::Tiny: 0.22
    Carp: 1.26
    Data::Section::Simple: 0.05
    Devel::FindPerl: 0.012
    Dist::Zilla: 4.300039
    Dist::Zilla::Plugin::ArchiveRelease: 4.00
    Dist::Zilla::Plugin::AutoPrereqs: 4.300039
    Dist::Zilla::Plugin::Bugtracker: 1.111080
    Dist::Zilla::Plugin::CheckChangesHasContent: 0.006
    Dist::Zilla::Plugin::CheckPrereqsIndexed: 0.008
    Dist::Zilla::Plugin::Clean: 0.07
    Dist::Zilla::Plugin::ConfirmRelease: 4.300039
    Dist::Zilla::Plugin::DualBuilders: 1.001
    Dist::Zilla::Plugin::ExecDir: 4.300039
    Dist::Zilla::Plugin::GatherDir: 4.300039
    Dist::Zilla::Plugin::GenerateFile: 4.300039
    Dist::Zilla::Plugin::Git::Commit: 2.013
    Dist::Zilla::Plugin::Git::CommitBuild: 2.013
    Dist::Zilla::Plugin::Git::NextVersion: 2.013
    Dist::Zilla::Plugin::Git::Push: 2.013
    Dist::Zilla::Plugin::Git::Tag: 2.013
    Dist::Zilla::Plugin::GithubMeta: 0.28
    Dist::Zilla::Plugin::Homepage: 1.101420
    Dist::Zilla::Plugin::InstallGuide: 1.200000
    Dist::Zilla::Plugin::License: 4.300039
    Dist::Zilla::Plugin::MakeMaker: 4.300039
    Dist::Zilla::Plugin::Manifest: 4.300039
    Dist::Zilla::Plugin::ManifestSkip: 4.300039
    Dist::Zilla::Plugin::MetaConfig: 4.300039
    Dist::Zilla::Plugin::MetaData::BuiltWith: 0.03000100
    Dist::Zilla::Plugin::MetaJSON: 4.300039
    Dist::Zilla::Plugin::MetaNoIndex: 4.300039
    Dist::Zilla::Plugin::MetaProvides::Package: 1.14000001
    Dist::Zilla::Plugin::MetaResources: 4.300039
    Dist::Zilla::Plugin::MetaTests: 4.300039
    Dist::Zilla::Plugin::MetaYAML: 4.300039
    Dist::Zilla::Plugin::MinimumPerl: 1.003
    Dist::Zilla::Plugin::ModuleBuild: 4.300039
    Dist::Zilla::Plugin::MojibakeTests: 0.5
    Dist::Zilla::Plugin::NextRelease: 4.300039
    Dist::Zilla::Plugin::OurPkgVersion: 0.004000
    Dist::Zilla::Plugin::PodCoverageTests: 4.300039
    Dist::Zilla::Plugin::PodSyntaxTests: 4.300039
    Dist::Zilla::Plugin::PodWeaver: 3.101641
    Dist::Zilla::Plugin::Prepender: 1.112280
    Dist::Zilla::Plugin::Prereqs::AuthorDeps: 0.002
    Dist::Zilla::Plugin::PruneCruft: 4.300039
    Dist::Zilla::Plugin::ReadmeAnyFromPod: 0.120120
    Dist::Zilla::Plugin::ReadmeFromPod: 0.18
    Dist::Zilla::Plugin::ReportPhase: 0.00
    Dist::Zilla::Plugin::ReportVersions::Tiny: 1.08
    Dist::Zilla::Plugin::Repository: 0.19
    Dist::Zilla::Plugin::RunExtraTests: 0.007
    Dist::Zilla::Plugin::ShareDir: 4.300039
    Dist::Zilla::Plugin::Test::CPAN::Changes: 0.005
    Dist::Zilla::Plugin::Test::CPAN::Meta::JSON: 0.003
    Dist::Zilla::Plugin::Test::Compile: 2.001
    Dist::Zilla::Plugin::Test::DistManifest: 2.000002
    Dist::Zilla::Plugin::Test::Kwalitee: 2.03
    Dist::Zilla::Plugin::Test::MinimumVersion: 2.000003
    Dist::Zilla::Plugin::Test::Perl::Critic: 2.112410
    Dist::Zilla::Plugin::Test::Pod::LinkCheck: 1.001
    Dist::Zilla::Plugin::Test::Portability: 2.000003
    Dist::Zilla::Plugin::Test::Synopsis: 2.000002
    Dist::Zilla::Plugin::Test::UnusedVars: 2.000003
    Dist::Zilla::Plugin::Test::Version: 0.002004
    Dist::Zilla::Plugin::TestRelease: 4.300039
    Dist::Zilla::Plugin::UploadToCPAN: 4.300039
    Exporter::Easy: 0.16
    File::Find: 1.20
    File::Temp: 0.2301
    FindBin: 1.51
    Log::Any: 0.15
    Log::Any::Adapter: 0.11
    Log::Any::Test: 0.15
    Module::Build: 0.4005
    Path::Tiny: 0.047
    Pod::Coverage::TrustPod: 0.100002
    TBX::Min: 0.06
    Test::Base: 0.60
    Test::CPAN::Meta: 0.23
    Test::Exception: 0.31
    Test::LongString: 0.15
    Test::More: 0.98
    Test::NoWarnings: 1.04
    Test::Pod: 1.45
    Test::Pod::Coverage: 1.08
    Test::XML: 0.08
    Try::Tiny: 0.12
    XML::Twig: 3.44
    autodie: 2.16
    perl: 'NA(skipped: perl)'
    strict: 1.07
    version: 0.9903
    warnings: 1.13
  perl:
    original: v5.16.1
    qv: 1
    version:
      - 5
      - 16
      - 1
  platform: MSWin32
x_Dist_Zilla:
  perl:
    version: 5.016001
  plugins:
    -
      class: Dist::Zilla::Plugin::ReportPhase
      name: Phase_Begins
      version: 0.00
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 2.013
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: GatherDir
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs::AuthorDeps
      name: Prereqs::AuthorDeps
      version: 0.002
    -
      class: Dist::Zilla::Plugin::GenerateFile
      name: MANIFEST.SKIP
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: ReportVersions::Tiny
      version: 1.08
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: Test::Perl::Critic
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: Test::DistManifest
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: Test::Version
      version: 0.002004
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: MetaTests
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: Test::CPAN::Meta::JSON
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: Test::MinimumVersion
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: MojibakeTests
      version: 0.5
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: Test::Portability
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: Test::Synopsis
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: Test::UnusedVars
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: Test::Pod::LinkCheck
      version: 1.001
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: Test::CPAN::Changes
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: Test::Kwalitee
      version: 2.03
    -
      class: Dist::Zilla::Plugin::Prepender
      name: Prepender
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: OurPkgVersion
      version: 0.004000
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: ShareDir
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: 1.003
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: Bugtracker
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: Homepage
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: 0
          show_uname: 0
      name: MetaData::BuiltWith
      version: 0.03000100
    -
      class: Dist::Zilla::Plugin::Repository
      name: Repository
      version: 0.19
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: MetaProvides::Package
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: MakeMaker
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: ModuleBuild
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::DualBuilders
      name: DualBuilders
      version: 1.001
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: 0.28
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: ReadmeFromPod
      version: 0.18
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmeMkdnInRoot
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: CheckChangesHasContent
      version: 0.006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CheckPrereqsIndexed
      version: 0.008
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: RunExtraTests
      version: 0.007
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: ArchiveRelease
      version: 4.00
    -
      class: Dist::Zilla::Plugin::Clean
      name: Clean
      version: 0.07
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: Git::Commit
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: Git::CommitBuild
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: Git::Tag
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: Git::Push
      version: 2.013
    -
      class: Dist::Zilla::Plugin::ReportPhase
      name: Phase_Ends
      version: 0.00
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300039
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300039
